#!/bin/sh

# Check code lint (backend side)
echo "Checking backend code lint "
(cd backend && npm run solhint && npm run prettier:solidity )
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
  echo "Code formatting issues found (backend). Commit aborted."
  exit 1
fi

# Check code lint (frontend side)
echo "Checking frontend code lint "
(cd frontend && npm run lint:prettier)
LINT_RESULT=$?

if [ $LINT_RESULT -ne 0 ]; then
  echo "Code formatting issues found (frontend). Commit aborted."
  exit 1
fi

# Check code code spell (backend & frontend side)
echo "Checking code spell for backend & frontend..."
( npx cspell "**" )
CSPELL_RESULT=$?

if [ $CSPELL_RESULT -ne 0 ]; then
  echo "Code spell issues found. Commit aborted."
  exit 1
fi

# Execute unit tests
echo "Running tests..."
(cd backend && npx hardhat test)
TEST_RESULT=$?

if [ $TEST_RESULT -ne 0 ]; then
  echo "Tests failed. Commit aborted."
  exit 1
fi

echo "All checks passed. Proceeding with commit."
exit 0