name: Test projet Alyra I4TKnetwork

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'

jobs:
  tests:
    name: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js 20.11.1
        uses: actions/setup-node@v1
        with:
          node-version: 20.11.1

      - name: Cache Node Modules
        id: cache-node-modules
        uses: actions/cache@v2
        with:
          path: 'backend/node_modules' # cache the node_modules in the project directory
          key: node_modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Install dependencies
        if: steps.cache-node-modules.outputs.cache-hit != 'true'
        run: |
          cd backend
          npm ci

      - name: Run Tests
        run: 
          cd backend && npx hardhat test --network hardhat